# Generated by Django 3.2.16 on 2023-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_Added_field_group_in_Post'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uq_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'user'), name='uq_following'),
        ),
    ]
