# Generated by Django 3.2.16 on 2023-03-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_Edit_constrains'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
    ]
