# Generated by Django 3.2.16 on 2023-03-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_Edit_constrains_v1'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uq_following',
        ),
    ]
