# Generated by Django 3.2.16 on 2023-03-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20230312_1924'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='uq_following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='uq_user_following'),
        ),
    ]
